config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :comments
  end
  resources :users  

  devise_for :users , :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  

resources :orders, only: [:index, :show, :new, :create]  

 post 'payments/create'
  
  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'

   root 'static_pages#landing_page'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bike Shop</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p> 

<div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>

<div class="navbar-collapse collapse">

	<ul class= "nav navbar-nav">

	<%= link_to "HOME", root_path %>
	<%= link_to "CONTACT", static_pages_contact_path %>
	<%= link_to "ABOUT", static_pages_about_path %>
	<%= link_to "PRODUCTS", products_path %>
  <%= form_tag("/products", method: "get") do %>   
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
  <% end %>
  
  <% if user_signed_in? %>  
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path) %>
    </li>
   <% end %>     

	</ul>

		</div> <!--end navbar header-->

	</div> <!--end navbar-collapse-->


<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>
<%= yield %>

</body>
</html>

app/views/layouts/product.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bike Shop</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery.raty', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'site', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar-header">

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </button>

<div class="navbar-collapse collapse">

	<ul class= "nav navbar-nav">

	<%= link_to "HOME", root_path %>
	<%= link_to "CONTACT", static_pages_contact_path %>
	<%= link_to "ABOUT", static_pages_about_path %>
	<%= link_to "PRODUCTS", products_path %>

	</ul>

		</div> <!--end navbar header-->

	</div> <!--end navbar-collapse-->


<h1>Welcome to Bike Berlin</h1>
<h2>Your source for used bikes in Berlin</h2>
<%= yield %>

</body>
</html>